/**
 * Which real screen each feature guide is written from. A feature maps to a route key of its panel; the route's page was captured from
 * the live product (screenshot and the labels, buttons, columns and filters actually on it), and the guide's steps are built from that.
 * "auto" marks a feature that works by itself (no steps), described with the screen where its effect shows.
 */
export interface PanelRoutes {
  /** route key → path under the panel's host */
  routes: Record<string, string>;
  /** feature name → route key, or [route key, "auto"] */
  map: Record<string, string | [string, "auto"]>;
  /** The sidebar label of the panel's own menu entry for a route key (for "Open X in the menu"). Filled from captured facts when absent. */
  menu?: Record<string, string>;
}

const A = (k: string): [string, "auto"] => [k, "auto"];

export const DOC_ROUTES: Record<string, PanelRoutes> = {
  workspace: {
    routes: { dashboard: "/workspace", analytics: "/workspace/analytics/hrms", notifications: "/workspace/notifications", documents: "/workspace/account/documents", setup: "/workspace/onboarding", profile: "/workspace/settings/profile", users: "/workspace/users", invite: "/workspace/invite", import: "/workspace/settings/import", branding: "/workspace/settings/branding", apps: "/workspace/settings/apps", domains: "/workspace/settings/domains", payments: "/workspace/settings/payments", automations: "/workspace/settings/automations", integrations: "/workspace/settings/integrations", audit: "/workspace/settings/audit-log", security: "/workspace/settings/security", sessions: "/workspace/account/sessions", billing: "/workspace/settings/billing", invoices: "/workspace/settings/billing/invoices", usage: "/workspace/settings/usage", upgrade: "/workspace/upgrade" },
    map: { "Executive dashboard": "dashboard", "Panel performance matrix": "dashboard", "Per-panel analytics": "analytics", Notifications: "notifications", Documents: "documents", "Company-wide search": A("dashboard"), "Guided company setup": "setup", "Organization profile": "profile", "Users, roles & seats": "users", Invitations: "invite", "Data import": "import", "Email verification": A("setup"), Branding: "branding", "Apps & downloads": "apps", "Custom domains": "domains", "Payment account": "payments", Automations: "automations", "Run history": "automations", Integrations: "integrations", "Signed webhooks": "automations", "Audit log": "audit", Security: "security", "Sessions & devices": "sessions", "Sign-in history": "sessions", "Roles & permissions": "users", "Plan & billing": "billing", "Invoices & payments": "invoices", Usage: "usage", Upgrade: "upgrade" },
  },
  lms: {
    routes: { dashboard: "/lms", leads: "/lms/leads", "lead-new": "/lms/leads/new", messages: "/lms/messages", applicants: "/lms/careers/applicants", campaigns: "/lms/campaigns", notifications: "/lms/notifications" },
    map: { Leads: "leads", "New lead": "lead-new", "Pipeline overview": "dashboard", "Pending tasks & stale-lead alerts": A("dashboard"), "Lead detail": "leads", "Saved filters": "dashboard", Messages: "messages", Applicants: "applicants", "Applicant detail": "applicants", Notifications: "notifications", "Website forms": A("leads"), "CSV import": "leads", "Lead & campaign analytics": "dashboard", "Campaign tracking": "campaigns", "Export current view": "dashboard" },
  },
  hrms: {
    routes: { dashboard: "/hrms", employees: "/hrms/employees", "employee-new": "/hrms/employees/new", departments: "/hrms/departments", recruitment: "/hrms/recruitment", attendance: "/hrms/attendance", leave: "/hrms/leave", holidays: "/hrms/holidays", payroll: "/hrms/payroll", payouts: "/hrms/payroll/payouts", analytics: "/hrms/analytics", settings: "/hrms/settings", me: "/hrms/me", "me-attendance": "/hrms/me/attendance", "me-leave": "/hrms/me/leave", "me-salary": "/hrms/me/salary", "me-documents": "/hrms/me/documents", "me-profile": "/hrms/me/profile", directory: "/hrms/me/directory", notifications: "/hrms/notifications" },
    map: { "Employee directory": "employees", "Add & edit employee": "employee-new", Departments: "departments", "Organisation tree": "departments", Recruitment: "recruitment", "Employee documents": "employees", Attendance: "attendance", Leave: "leave", Holidays: "holidays", "Payroll runs": "payroll", "Salary revisions": "payroll", Payslips: "payroll", "Salary payouts": "payouts", "My dashboard": "me", "My attendance": "me-attendance", "My leave": "me-leave", "My salary & payslips": "me-salary", "My documents & profile": "me-documents", "Company directory": "directory", "HR analytics": "analytics", Settings: "settings", Notifications: "notifications", "Audit trail": A("dashboard") },
  },
  fms: {
    routes: { dashboard: "/fms", receivables: "/fms/receivables", invoices: "/fms/invoices", "credit-notes": "/fms/credit-notes", receipts: "/fms/receipts", "payment-links": "/fms/payment-links", refunds: "/fms/refunds", customers: "/fms/customers", payables: "/fms/payables", bills: "/fms/bills", "debit-notes": "/fms/debit-notes", payouts: "/fms/payouts", vendors: "/fms/vendors", beneficiaries: "/fms/beneficiaries", advances: "/fms/advances", "employee-expenses": "/fms/employee-expenses", "salary-payments": "/fms/salary-payments", "payroll-runs": "/fms/payroll-runs", "bank-accounts": "/fms/bank-accounts", "cash-accounts": "/fms/cash-accounts", transfers: "/fms/transfers", "bank-reconciliation": "/fms/bank-reconciliation", "cash-reconciliation": "/fms/cash-reconciliation", transactions: "/fms/transactions", ledger: "/fms/general-ledger", "trial-balance": "/fms/trial-balance", pnl: "/fms/reports/profit-and-loss", "balance-sheet": "/fms/reports/balance-sheet", "cash-flow": "/fms/reports/cash-flow", tax: "/fms/reports/tax", budget: "/fms/reports/budget-vs-actual", "project-profitability": "/fms/reports/project-profitability", revenue: "/fms/reports/revenue", expense: "/fms/reports/expense", approvals: "/fms/approvals", "approval-rules": "/fms/settings/approvals", accounts: "/fms/settings/accounts", "fiscal-periods": "/fms/settings/fiscal-periods", numbering: "/fms/settings/numbering", "tax-config": "/fms/settings/tax-config", "exchange-rates": "/fms/settings/exchange-rates", "payment-methods": "/fms/settings/payment-methods", "asset-expenses": "/fms/asset-expenses", "panel-prms": "/fms/panels/prms", "panel-pms": "/fms/panels/pms", "panel-hrms": "/fms/panels/hrms", "panel-tms": "/fms/panels/tms" },
    map: { Receivables: "receivables", Invoices: "invoices", "Credit notes": "credit-notes", Receipts: "receipts", "Payment links": "payment-links", Refunds: "refunds", Customers: "customers", Payables: "payables", Bills: "bills", "Debit notes": "debit-notes", Payouts: "payouts", "Vendors & bank directory": "beneficiaries", "Advances & employee expenses": "employee-expenses", "Salary payments & payroll runs": "payroll-runs", "Bank accounts": "bank-accounts", "Cash accounts": "cash-accounts", Transfers: "transfers", "Bank reconciliation": "bank-reconciliation", "Cash reconciliation": "cash-reconciliation", Transactions: "transactions", "General ledger": "ledger", "Trial balance": "trial-balance", "Profit & loss": "pnl", "Balance sheet": "balance-sheet", "Cash flow": "cash-flow", "Tax reports": "tax", "Budget vs actual": "budget", "Project profitability": "project-profitability", "Revenue & expense reports": "revenue", Approvals: "approvals", "Approval rules": "approval-rules", "Chart of accounts": "accounts", "Fiscal periods": "fiscal-periods", Numbering: "numbering", "Tax configuration": "tax-config", "Exchange rates": "exchange-rates", "Payment methods": "payment-methods", "Asset expenses": "asset-expenses", Procurement: "panel-prms", Projects: "panel-pms", "HR & payroll": "panel-hrms", Training: "panel-tms" },
  },
  pms: {
    routes: { dashboard: "/pms", projects: "/pms/projects", "project-new": "/pms/projects/new", calendar: "/pms/calendar", clients: "/pms/clients", timesheets: "/pms/timesheets", costing: "/pms/costing", analytics: "/pms/analytics", settings: "/pms/settings", "me-projects": "/pms/me/projects", "me-tasks": "/pms/me/tasks", "me-timesheet": "/pms/me/timesheet", notifications: "/pms/notifications" },
    map: { Projects: "projects", "Project board": "projects", "Task lists": "projects", Timeline: "projects", Calendar: "calendar", "Project documents": "projects", Clients: "clients", Timesheets: "timesheets", Costing: "costing", Milestones: "projects", "Overdue warnings": A("dashboard"), "My projects": "me-projects", "My tasks": "me-tasks", "My timesheet": "me-timesheet", Notifications: "notifications", "Project analytics": "analytics", Settings: "settings" },
  },
  prms: {
    routes: { dashboard: "/prms", requisitions: "/prms/requisitions", rfq: "/prms/rfq", "purchase-orders": "/prms/purchase-orders", grn: "/prms/grn", invoices: "/prms/invoices", payments: "/prms/payments", contracts: "/prms/contracts", vendors: "/prms/vendors", expenses: "/prms/expenses", budgets: "/prms/budgets", "third-party": "/prms/third-party", reports: "/prms/reports", assets: "/prms/assets", subscriptions: "/prms/subscriptions", infrastructure: "/prms/infrastructure", inventory: "/prms/inventory", "me-requisitions": "/prms/me/requisitions", "me-expenses": "/prms/me/expenses" },
    map: { "Purchase requests": "requisitions", RFQs: "rfq", "Purchase orders": "purchase-orders", "Goods receipt (GRN)": "grn", "Vendor invoices": "invoices", Payments: "payments", Contracts: "contracts", Vendors: "vendors", Expenses: "expenses", Budgets: "budgets", "Third-party services": "third-party", "Procurement analytics & reports": "reports", "Hardware & assets": "assets", Subscriptions: "subscriptions", Infrastructure: "infrastructure", Inventory: "inventory", "My requests": "me-requisitions", "My expenses": "me-expenses" },
  },
  tms: {
    routes: { dashboard: "/tms", programs: "/tms/programs", batches: "/tms/batches", "batch-calendar": "/tms/batches/calendar", students: "/tms/students", applications: "/tms/applications", classes: "/tms/classes", projects: "/tms/projects", assignments: "/tms/assignments", certificates: "/tms/certificates", payments: "/tms/payments", placements: "/tms/placements", reports: "/tms/reports", me: "/tms/me", "me-program": "/tms/me/program", "me-batch": "/tms/me/batch", "me-schedule": "/tms/me/schedule", "me-assignments": "/tms/me/assignments", "me-projects": "/tms/me/projects", "me-certificates": "/tms/me/certificates", "me-payments": "/tms/me/payments", "me-profile": "/tms/me/profile" },
    map: { Programs: "programs", Batches: "batches", "Batch calendar": "batch-calendar", Students: "students", Applications: "applications", Classes: "classes", Projects: "projects", Assignments: "assignments", "Mentor tools": "classes", Certificates: "certificates", Payments: "payments", Placements: "placements", Reports: "reports", "My dashboard": "me", "My program & batch": "me-program", "Class schedule": "me-schedule", "My assignments & projects": "me-assignments", "My certificates": "me-certificates", "My payments": "me-payments", Profile: "me-profile" },
  },
  messenger: {
    routes: { dashboard: "/messenger", dm: "/messenger/dm", channels: "/messenger/channels", projects: "/messenger/projects", groups: "/messenger/groups", announcements: "/messenger/announcements", files: "/messenger/files", meetings: "/messenger/meetings", search: "/messenger/search", settings: "/messenger/settings" },
    map: { "Direct messages": "dm", "Team channels": "channels", "Project channels": "projects", "Group chats": "groups", "Unread counts": A("dashboard"), Announcements: "announcements", "Shared files": "files", Meetings: "meetings", Search: "search", "Presence & notifications": A("dashboard"), Settings: "settings", "Activity trail": A("dashboard") },
  },
  sop: {
    routes: { dashboard: "/sop", library: "/sop/library", "library-new": "/sop/library/new", my: "/sop/my", assigned: "/sop/assigned", departments: "/sop/departments", categories: "/sop/categories", templates: "/sop/templates", compliance: "/sop/compliance", reports: "/sop/reports", settings: "/sop/settings" },
    map: { "SOP library": "library", "New SOP": "library-new", "My SOPs": "my", "Assigned SOPs": "assigned", "Version history": "library", Departments: "departments", Categories: "categories", Templates: "templates", Assignments: "assigned", "Acknowledgement tracking": "compliance", "Compliance reports": "compliance", "Review & expiry schedule": "compliance", Feedback: "library", "Reports & analytics": "reports", "Settings & audit trail": "settings" },
  },
  lpms: {
    routes: { dashboard: "/lpms", documents: "/lpms/documents", new: "/lpms/new", approvals: "/lpms/approvals", signatures: "/lpms/signatures", templates: "/lpms/templates", makers: "/lpms/makers", workflows: "/lpms/workflows", categories: "/lpms/categories", settings: "/lpms/settings" },
    map: { "Document library": "documents", "New document": "new", Approvals: "approvals", Signatures: "signatures", "Document history": "documents", Templates: "templates", "Maker types": "makers", Workflows: "workflows", Categories: "categories", Settings: "settings", "Audit trail": A("dashboard"), Notifications: A("dashboard") },
  },
  dlms: {
    routes: { dashboard: "/dlms", company: "/dlms/company", clients: "/dlms/clients", credentials: "/dlms/credentials", documents: "/dlms/documents", urls: "/dlms/urls", notes: "/dlms/notes", expiry: "/dlms/expiry", settings: "/dlms/settings" },
    map: { "Company vault": "company", "Client vaults": "clients", "Credential vault": "credentials", "Document vault": "documents", "URLs & accounts": "urls", Notes: "notes", "Encryption at rest": A("credentials"), "Per-record access": A("credentials"), "Expiry & alerts": "expiry", "Activity log": A("dashboard"), Settings: "settings" },
  },
  ots: {
    routes: { dashboard: "/ots", tests: "/ots/tests", "test-new": "/ots/tests/new", questions: "/ots/questions", "questions-import": "/ots/questions/import", assignments: "/ots/assignments", results: "/ots/results", certificates: "/ots/certificates", reports: "/ots/reports", analytics: "/ots/analytics", "my-tests": "/ots/my-tests", "my-results": "/ots/my-results", settings: "/ots/settings" },
    map: { Tests: "tests", "New test": "test-new", "Question bank": "questions", "Question import": "questions-import", "Test assignments": "assignments", Results: "results", "Evaluator workflow": "results", Certificates: "certificates", "Test reports & analytics": "reports", "Hiring screening": A("assignments"), "My tests": "my-tests", "My results": "my-results", "Question & test categories": "settings", "Settings & activity log": "settings" },
  },
  aibots: {
    routes: { dashboard: "/aibots", bots: "/aibots/bots", "bot-new": "/aibots/bots/new", chats: "/aibots/chats", settings: "/aibots/settings" },
    map: { "Create bot": "bot-new", "Start new chat": "dashboard", "Find a bot": "bots", "Knowledge files": "bot-new", "Manage bots": "bots", "Access modes per bot": "bot-new", "All chats": "chats", "Usage & cost": "dashboard", Settings: "settings", "Audit trail": A("dashboard") },
  },
  intelligence: {
    routes: { dashboard: "/intelligence" },
    map: { "Plain-language questions": "dashboard", "Answers from live data": A("dashboard"), "Tables, charts & KPIs": A("dashboard"), "How this was calculated": A("dashboard"), "Suggested questions": "dashboard", "Access respected": A("dashboard"), "Sensitive fields withheld": A("dashboard"), Conversations: "dashboard", "Usage metering": A("dashboard") },
  },
  smms: {
    routes: { dashboard: "/smms", campaigns: "/smms/campaigns", "campaign-new": "/smms/campaigns/new", posts: "/smms/posts", "post-new": "/smms/posts/new", media: "/smms/media", ai: "/smms/ai", analytics: "/smms/analytics", settings: "/smms/settings" },
    map: { "Campaigns & ads": "campaigns", "Social media posts": "posts", "New post & new campaign": "post-new", "Media library": "media", "AI content generator": "ai", "Tone refinement": "ai", "Approval workflow": "posts", "Calendar & scheduling": "posts", "Platform connections": "settings", Analytics: "analytics", Settings: "settings", "Activity trail": A("dashboard") },
  },
  seo: {
    routes: { dashboard: "/seo", overview: "/seo/overview", audit: "/seo/audit", technical: "/seo/technical", "on-page": "/seo/on-page", content: "/seo/content", pages: "/seo/pages", keywords: "/seo/keywords", rankings: "/seo/rankings", competitors: "/seo/competitors", "internal-links": "/seo/internal-links", backlinks: "/seo/backlinks", sitemap: "/seo/sitemap", robots: "/seo/robots", schema: "/seo/schema", issues: "/seo/issues", tasks: "/seo/tasks", reports: "/seo/reports", settings: "/seo/settings" },
    map: { "SEO overview": "overview", "Website audit": "audit", "Technical SEO": "technical", "On-page SEO": "on-page", "Content SEO": "content", Pages: "pages", Keywords: "keywords", Rankings: "rankings", Competitors: "competitors", "Internal links": "internal-links", Backlinks: "backlinks", Sitemap: "sitemap", "Robots.txt": "robots", "Schema / structured data": "schema", "SEO issues": "issues", "SEO tasks": "tasks", Reports: "reports", "Settings & audit trail": "settings" },
  },
  cms: {
    routes: { dashboard: "/cms", pages: "/cms/pages", blog: "/cms/collections/blog", jobs: "/cms/collections/jobs", engagement: "/cms/collections/engagement", products: "/cms/collections/products", forms: "/cms/forms", media: "/cms/media", theme: "/cms/theme", navigation: "/cms/navigation", footer: "/cms/footer", identity: "/cms/site-identity", seo: "/cms/seo", settings: "/cms/settings", offers: "/cms/offers", "offer-new": "/cms/offers/new", coupons: "/cms/offers/coupons", claims: "/cms/offers/claims", subscribers: "/cms/offers/subscribers", wallet: "/cms/wallet", "wallet-rules": "/cms/wallet/rules", referrals: "/cms/wallet/referrals", "referral-campaigns": "/cms/wallet/campaigns", "usage-rules": "/cms/wallet/usage-rules", wallets: "/cms/wallet/wallets", ledger: "/cms/wallet/ledger", push: "/cms/push", chatbot: "/cms/chatbot", "chatbot-conversations": "/cms/chatbot/conversations", "chatbot-kb": "/cms/chatbot/knowledge-base", "chatbot-config": "/cms/chatbot/config", voice: "/cms/chatbot/voice", "voice-config": "/cms/chatbot/voice/config", "voice-conversations": "/cms/chatbot/voice/conversations", collections: "/cms/collections" },
    map: { Pages: "pages", Services: "pages", "Blog posts": "blog", Careers: "jobs", "Hiring models": "engagement", Products: "products", Forms: "forms", "Media library": "media", Themes: "theme", Customize: "theme", Menus: "navigation", Footer: "footer", "Site identity": "identity", "Festival offers": "offers", "Wallet & credits": "wallet", "Referral campaigns": "referral-campaigns", "Usage rules": "usage-rules", "Push notifications": "push", "SEO overview": "seo", "AI chatbot": "chatbot", "Knowledge base": "chatbot-kb", "AI config": "chatbot-config", "Conversation AI": "voice", "Voice config": "voice-config", Conversations: "chatbot-conversations", Settings: "settings", Collections: "collections", "Draft & approval": A("pages"), "Audit trail": A("dashboard") },
  },
  website: {
    routes: { domains: "/workspace/settings/domains", pages: "/cms/pages", settings: "/cms/settings", forms: "/cms/forms", seo: "/cms/seo" },
    map: { "Your own domain": "domains", "Automatic SSL": A("domains"), "Maintenance mode": "settings", "Built-in lead capture": "forms", "SEO built in": "seo" },
  },
  support: {
    routes: { dashboard: "/support", assistant: "/support/assistant", help: "/support/help", "request-new": "/support/requests/new", requests: "/support/requests" },
    map: { "Help assistant": "assistant", "Help center": "help", "Turn a chat into a request": "assistant", "New request": "request-new", "My requests": "requests", Notifications: "dashboard" },
  },
  // The Client Portal is signed in to by the company's clients, students and applicants, so it has no staff screens to capture.
  portal: { routes: {}, map: {} },
};
