import "server-only";
import { head } from "@vercel/blob";
import { putObject, deleteObject } from "@/lib/storage/blob";
import { COLLECTIONS, smmsCollection, newId, createStamp, updateStamp, notDeleted, str, strList, escapeRegex, type Stamps } from "@/lib/smms/db";
import { IMAGE_TYPES, VIDEO_TYPES, MAX_IMAGE_BYTES, MAX_VIDEO_BYTES, isPlatform, type MediaKind } from "@/lib/smms/constants";
import { SmmsInputError, NotFoundError } from "@/lib/smms/viewer";

/**
 * The central media library: every image and video used by an ad or a post.
 * Files live in the platform's shared private Vercel Blob store (the same
 * `lib/storage/blob.ts` core every other panel uses) under `smms/`; they are
 * only ever served through the authenticated `/api/smms/media/[id]` route, or
 * to a publishing platform through a short-lived signed URL.
 *
 * Uploads go browser → Blob directly (client upload, see
 * `/api/smms/media/upload`) so videos aren't capped by the 4.5 MB function
 * body limit; the browser then registers the finished blob here, and the
 * server re-reads its real size and type from Blob before trusting it.
 */

export const MEDIA_FOLDER = "smms";

export interface MediaVersion {
  storageKey: string;
  contentType: string;
  size: number;
  replacedAt: Date;
  replacedBy: string | null;
}

export interface MediaDoc extends Stamps {
  _id: string;
  kind: MediaKind;
  name: string;
  description: string;
  altText: string;
  tags: string[];
  /** Intended platform, if any (a filter aid only). */
  platform: string | null;
  storageKey: string;
  contentType: string;
  size: number;
  width: number | null;
  height: number | null;
  durationSec: number | null;
  source: "upload" | "ai";
  /** The prompt an AI image was generated from / the creative prompt for a real image. */
  creativePrompt: string;
  /** Video only: an image media item used as its thumbnail. */
  thumbnailId: string | null;
  /** Video only. */
  script: string;
  caption: string;
  versions: MediaVersion[];
}

let indexesEnsured = false;
export async function mediaCollection() {
  const col = await smmsCollection<MediaDoc>(COLLECTIONS.media);
  if (!indexesEnsured) {
    indexesEnsured = true;
    await Promise.all([col.createIndex({ deletedAt: 1, createdAt: -1 }).catch(() => {}), col.createIndex({ kind: 1, deletedAt: 1 }).catch(() => {}), col.createIndex({ storageKey: 1 }).catch(() => {})]);
  }
  return col;
}

/** Upload pathnames are generated by the browser but must look exactly like this — checked when the upload token is issued and again on register. */
export const UPLOAD_PATH = /^smms\/uploads\/[0-9a-f-]{36}\.(jpg|png|webp|gif|mp4|mov|webm)$/;

export function kindForType(contentType: string): MediaKind | null {
  if (IMAGE_TYPES[contentType]) return "image";
  if (VIDEO_TYPES[contentType]) return "video";
  return null;
}

export interface MediaFilter {
  q?: string;
  kind?: string;
  source?: string;
  platform?: string;
  page?: number;
  pageSize?: number;
}

export async function listMedia(f: MediaFilter = {}) {
  const col = await mediaCollection();
  const filter: Record<string, unknown> = { ...notDeleted };
  if (f.kind === "image" || f.kind === "video") filter.kind = f.kind;
  if (f.source === "upload" || f.source === "ai") filter.source = f.source;
  if (f.platform && isPlatform(f.platform)) filter.platform = f.platform;
  if (f.q) {
    const rx = new RegExp(escapeRegex(f.q), "i");
    filter.$or = [{ name: rx }, { description: rx }, { tags: rx }, { caption: rx }];
  }
  const page = Math.max(f.page ?? 1, 1);
  const pageSize = Math.min(Math.max(f.pageSize ?? 36, 1), 100);
  const [items, total] = await Promise.all([col.find(filter).sort({ createdAt: -1 }).skip((page - 1) * pageSize).limit(pageSize).toArray(), col.countDocuments(filter)]);
  return { items, total, page, pageSize, totalPages: Math.max(Math.ceil(total / pageSize), 1) };
}

export async function getMedia(id: string): Promise<MediaDoc | null> {
  if (!id) return null;
  const col = await mediaCollection();
  return col.findOne({ _id: id, ...notDeleted });
}

export async function getMediaMany(ids: string[]): Promise<MediaDoc[]> {
  const wanted = [...new Set(ids.filter(Boolean))];
  if (wanted.length === 0) return [];
  const col = await mediaCollection();
  const rows = await col.find({ _id: { $in: wanted }, ...notDeleted }).toArray();
  const byId = new Map(rows.map((r) => [r._id, r]));
  return wanted.map((id) => byId.get(id)).filter((m): m is MediaDoc => Boolean(m));
}

/** Reads the uploaded blob's real metadata from Blob (never trusts the browser's claims). */
async function inspectUpload(pathname: string): Promise<{ contentType: string; size: number; kind: MediaKind }> {
  if (!UPLOAD_PATH.test(pathname)) throw new SmmsInputError("That upload isn't valid.");
  let meta;
  try {
    meta = await head(pathname);
  } catch {
    throw new SmmsInputError("The upload didn't finish — please try again.");
  }
  const contentType = meta.contentType.split(";")[0].trim().toLowerCase();
  const kind = kindForType(contentType);
  if (!kind) {
    await deleteObject(pathname);
    throw new SmmsInputError("Only JPG, PNG, WebP, GIF, MP4, MOV and WebM files are supported.");
  }
  if (meta.size > (kind === "image" ? MAX_IMAGE_BYTES : MAX_VIDEO_BYTES)) {
    await deleteObject(pathname);
    throw new SmmsInputError("That file is too large.");
  }
  return { contentType, size: meta.size, kind };
}

export interface MediaMetaInput {
  name?: unknown;
  description?: unknown;
  altText?: unknown;
  tags?: unknown;
  platform?: unknown;
  width?: unknown;
  height?: unknown;
  durationSec?: unknown;
  creativePrompt?: unknown;
  script?: unknown;
  caption?: unknown;
  thumbnailId?: unknown;
}

const dim = (v: unknown): number | null => {
  const n = Math.round(Number(v));
  return Number.isFinite(n) && n > 0 && n < 100000 ? n : null;
};

export async function registerUpload(pathname: string, meta: MediaMetaInput, actorId: string): Promise<MediaDoc> {
  const col = await mediaCollection();
  if (await col.findOne({ storageKey: pathname })) throw new SmmsInputError("That upload is already in the library.");
  const info = await inspectUpload(pathname);
  const doc: MediaDoc = {
    _id: newId(),
    kind: info.kind,
    name: str(meta.name, 160) || "Untitled",
    description: str(meta.description, 2000),
    altText: str(meta.altText, 500),
    tags: strList(meta.tags, 20, 40),
    platform: isPlatform(meta.platform) ? meta.platform : null,
    storageKey: pathname,
    contentType: info.contentType,
    size: info.size,
    width: dim(meta.width),
    height: dim(meta.height),
    durationSec: info.kind === "video" ? dim(meta.durationSec) : null,
    source: "upload",
    creativePrompt: str(meta.creativePrompt, 4000),
    thumbnailId: null,
    script: "",
    caption: "",
    versions: [],
    ...createStamp(actorId),
  };
  await col.insertOne(doc);
  return doc;
}

/** Swap the file behind a media item. The old blob is kept as a version (never deleted), so posts that used it are unaffected in history. */
export async function replaceMediaFile(id: string, pathname: string, meta: MediaMetaInput, actorId: string): Promise<{ before: MediaDoc; after: MediaDoc }> {
  const col = await mediaCollection();
  const before = await getMedia(id);
  if (!before) throw new NotFoundError();
  const info = await inspectUpload(pathname);
  if (info.kind !== before.kind) {
    await deleteObject(pathname);
    throw new SmmsInputError(`Replace a ${before.kind} with another ${before.kind}.`);
  }
  const version: MediaVersion = { storageKey: before.storageKey, contentType: before.contentType, size: before.size, replacedAt: new Date(), replacedBy: actorId };
  await col.updateOne(
    { _id: id },
    {
      $set: { storageKey: pathname, contentType: info.contentType, size: info.size, width: dim(meta.width), height: dim(meta.height), durationSec: info.kind === "video" ? dim(meta.durationSec) : null, source: "upload", ...updateStamp(actorId) },
      $push: { versions: { $each: [version], $slice: -20 } },
    }
  );
  return { before, after: (await getMedia(id))! };
}

export async function saveAiImage(buf: Buffer, meta: { name: string; creativePrompt: string; platform: string | null; width: number; height: number; tags?: string[] }, actorId: string): Promise<MediaDoc> {
  const col = await mediaCollection();
  const id = newId();
  const put = await putObject(`${MEDIA_FOLDER}/ai`, `${id}.png`, buf, "image/png");
  const doc: MediaDoc = {
    _id: id,
    kind: "image",
    name: meta.name.slice(0, 160) || "AI image",
    description: "",
    altText: "",
    tags: ["ai", ...(meta.tags ?? [])].slice(0, 20),
    platform: meta.platform && isPlatform(meta.platform) ? meta.platform : null,
    storageKey: put.storageKey,
    contentType: "image/png",
    size: put.size,
    width: meta.width,
    height: meta.height,
    durationSec: null,
    source: "ai",
    creativePrompt: meta.creativePrompt.slice(0, 4000),
    thumbnailId: null,
    script: "",
    caption: "",
    versions: [],
    ...createStamp(actorId),
  };
  await col.insertOne(doc);
  return doc;
}

export async function updateMediaMeta(id: string, meta: MediaMetaInput, actorId: string): Promise<{ before: MediaDoc; after: MediaDoc }> {
  const col = await mediaCollection();
  const before = await getMedia(id);
  if (!before) throw new NotFoundError();
  let thumbnailId: string | null = before.thumbnailId;
  if (before.kind === "video" && meta.thumbnailId !== undefined) {
    const tid = str(meta.thumbnailId, 64);
    if (tid) {
      const t = await getMedia(tid);
      if (!t || t.kind !== "image") throw new SmmsInputError("A thumbnail must be an image from the library.");
      thumbnailId = t._id;
    } else thumbnailId = null;
  }
  const set = {
    name: str(meta.name, 160) || before.name,
    description: str(meta.description, 2000),
    altText: str(meta.altText, 500),
    tags: strList(meta.tags, 20, 40),
    platform: isPlatform(meta.platform) ? meta.platform : null,
    creativePrompt: str(meta.creativePrompt, 4000),
    script: before.kind === "video" ? str(meta.script, 20000) : "",
    caption: str(meta.caption, 5000),
    thumbnailId,
    ...(meta.width !== undefined ? { width: dim(meta.width), height: dim(meta.height) } : {}),
    ...(meta.durationSec !== undefined && before.kind === "video" ? { durationSec: dim(meta.durationSec) } : {}),
    ...updateStamp(actorId),
  };
  await col.updateOne({ _id: id }, { $set: set });
  return { before, after: (await getMedia(id))! };
}

/** Where a media item is attached — deletion is refused while anything live still uses it. */
export async function mediaUsage(id: string): Promise<{ ads: { _id: string; name: string; campaignId: string }[]; posts: { _id: string; title: string }[]; videos: { _id: string; name: string }[] }> {
  const [ads, posts, media] = await Promise.all([
    smmsCollection<{ _id: string; name: string; campaignId: string; mediaIds: string[]; thumbnailId: string | null; deletedAt: Date | null }>(COLLECTIONS.ads),
    smmsCollection<{ _id: string; title: string; mediaIds: string[]; thumbnailId: string | null; deletedAt: Date | null }>(COLLECTIONS.posts),
    mediaCollection(),
  ]);
  const [a, p, v] = await Promise.all([
    ads.find({ ...notDeleted, $or: [{ mediaIds: id }, { thumbnailId: id }] }, { projection: { name: 1, campaignId: 1 } }).limit(20).toArray(),
    posts.find({ ...notDeleted, $or: [{ mediaIds: id }, { thumbnailId: id }] }, { projection: { title: 1 } }).limit(20).toArray(),
    media.find({ ...notDeleted, thumbnailId: id }, { projection: { name: 1 } }).limit(20).toArray(),
  ]);
  return { ads: a.map((x) => ({ _id: x._id, name: x.name, campaignId: x.campaignId })), posts: p.map((x) => ({ _id: x._id, title: x.title })), videos: v.map((x) => ({ _id: x._id, name: x.name })) };
}

export async function deleteMedia(id: string, actorId: string): Promise<MediaDoc> {
  const m = await getMedia(id);
  if (!m) throw new NotFoundError();
  const usage = await mediaUsage(id);
  const n = usage.ads.length + usage.posts.length + usage.videos.length;
  if (n > 0) throw new SmmsInputError(`This ${m.kind} is attached to ${n} item${n === 1 ? "" : "s"} — detach it first.`);
  const col = await mediaCollection();
  // Soft delete: blobs are kept, like every other panel's documents.
  await col.updateOne({ _id: id }, { $set: { deletedAt: new Date(), ...updateStamp(actorId) } });
  return m;
}

/** Media ids from a client, filtered to real, live library items of the allowed kinds. */
export async function validMediaIds(ids: unknown, kinds: MediaKind[] = ["image", "video"]): Promise<string[]> {
  const list = Array.isArray(ids) ? ids.filter((x): x is string => typeof x === "string").slice(0, 10) : [];
  const rows = await getMediaMany(list);
  return rows.filter((m) => kinds.includes(m.kind)).map((m) => m._id);
}

export interface MediaCard {
  _id: string;
  kind: MediaKind;
  name: string;
  contentType: string;
  size: number;
  width: number | null;
  height: number | null;
  durationSec: number | null;
  source: "upload" | "ai";
  thumbnailId: string | null;
  altText: string;
  updatedAt: string;
}

export function toMediaCard(m: MediaDoc): MediaCard {
  return { _id: m._id, kind: m.kind, name: m.name, contentType: m.contentType, size: m.size, width: m.width, height: m.height, durationSec: m.durationSec, source: m.source, thumbnailId: m.thumbnailId, altText: m.altText, updatedAt: m.updatedAt.toISOString() };
}
